### ISSUE TITLE
Update cluster section of RA-MANUAL 

### ISSUE THREAD

**Issue by Houdanait** [gslab-econ/ra-manual-archived#10]
Hello @jmshapir @gentzkow, 
I have been setting up a new repository on Sherlock these past days and have run into some errors/issues most of which are related to not knowing how to do it and implied more than needed time spent on this. 
I believe that it might be worth updating the [cluster section](https://github.com/gslab-econ/ra-manual/wiki/Clusters) of the manual to provide more accurate/ guidance on how to run repos on Sherlock (also because some of the links in that section are broken/no longer relevant). This would allow future RA/users to turn to the manual and have accurate information plus avoid running into similar issues. 

If you are fine with updating the section, I can propose some amendments to you and if you agree I can go ahead and ammend.

**Comment by Houdanait** [comment]
In the below  : 

1. I have removed references to Chicago Cluster computer
2. I have updated the broken references to existing ones
3. I have ammended some of the text in sections, but mostly added a section about setting up and testing the environment before even testing on a subset of the data.

[ClusterSection.md.zip](https://github.com/gslab-econ/ra-manual/files/6232728/ClusterSection.md.zip)

**Comment by gentzkow** [comment]
Thanks @houdanait! I appreciate your taking this on. We are just about to
deprecate this RA manual in favor of the /gentzkow_ra_manual/ flavor here
<https://github.com/gentzkow/ra-manual/wiki>. So it would be great if you
could port over any changes you make to the latter as well.

It's probably a good idea to check w/ others in the lab to make sure they
also agree that the revisions reflect best practices for running things on
Sherlock. You might also ping some of the current PhD students who use
Sherlock to get their input as well.

**Comment by Houdanait** [comment]
@gentzkow Ok great!!! I will check with others and get back on this!

**Comment by Houdanait** [comment]
Hello @gentzkow ! I have had some great feedback from Jacob, Luis and Reese! I have implemented their suggestions in this MD (zipped here) 
Let me know what you think whenever you have had the time to look at it, and then if I can implement the change. 
[ClusterSection 2.md.zip](https://github.com/gslab-econ/ra-manual/files/6244695/ClusterSection.2.md.zip)

**Comment by gentzkow** [comment]
Thanks @Houdanait. Pretty good. 

Let's delete the sentence "Note that the only exception is on submitting make.sbatch script because we have not integrated SCons with SLURM yet." We are trying to keep the RA manual neutral on which template is being used; we are therefore not mentioning specific tools like SCons and make.py at all.

Shouldn't "Setting up the environment" go before "Running jobs"?

It feels to me like this is more long-winded than it needs to be and could benefit from improved organization. Why don't you see if you can reduce the total text by ~30% while keeping the information the same.

**Comment by Houdanait** [comment]
Closing this issue since we have moved the ra-manual to a new [location](https://github.com/gslab-econ/ra-manual) . 
The discussion and goal of this issue hence continue in the similar issue in that repo, namely [issue 2](https://github.com/gslab-econ/ra-manual/issues/2)
